### PR TITLE
Add ARM instruction to get started guide

### PR DESCRIPTION
**Pull request by nanikjava**
Issue : #306 

ARM instruction are now added inside the doc. Below is screenshot how it looks like based on the PR changes.

Screenshot from 2020-10-13 13-45-23
Screenshot from 2020-10-13 13-45-33

### CODE REVIEW

**Comment by nanikjava** [comment]
To run `mkdocs` using Docker following is the Dockerfile

```
FROM python:3.9
COPY ./mkdocs.yml/ /
COPY ./docs/ /mkdocs/
COPY ./docs/ /docs/
COPY ./CONTRIBUTING.md /
COPY ./CODE_OF_CONDUCT.md /
COPY ./LICENSE /
COPY ./MAINTAINERS /
WORKDIR /
RUN pip install mkdocs
RUN pip install mkdocs-material-extensions
EXPOSE 8080
CMD ["mkdocs", "serve","-f","mkdocs.yml","-a","0.0.0.0:8080"]
# mkdocs serve -f mkdocs.yml
```

Build the Dockerfile with the command

```
docker build -t mkdocs:latest .
```

and to run it

```
docker run -p 8888:8080  mkdocs:latest
```

**Review by stefanprodan — COMMENTED** [review]
Can please remove the hint under production, one ARM reference is enough.

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @nanikjava

**Comment by nanikjava** [comment]
@stefanprodan do you mind adding the label `hacktoberfest-accepted' ? thank you.

**Pull request merged**
