### PR TITLE
explain a bit more about Flux Toolkit

### PR DESCRIPTION
**Pull request by dholbach**
Point to #flux-dev, point to video and relevant repositories.

### CODE REVIEW

**Comment by dholbach** [comment]
Do we want to include CONTRIBUTING.md in the navigation as well?

**Comment by hiddeco** [comment]
@dholbach yes, I think we do. The document still makes mention of the `#flux` Slack channel while you changed it to `#flux-dev` in the `README.md`.

**Comment by dholbach** [comment]
Shall we move CONTRIBUTING.md under docs? Or shall we symlink it somewhere?

Re: flux and flux-dev: do we want a separation between users (regular #flux) and contributors (#flux-dev)? In that case, it should be fine.

**Comment by dholbach** [comment]
→ went for the symlink approach, LMK if that works for you

**Pull request merged**
